### ISSUE TITLE
Unable to make data ontology on PostgreSQL

### ISSUE THREAD

**Issue by schuemie** [BenGlicksberg/ROMOP#1]
When I run `makeDataOntology`, i get the following error:

```r
Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  relation "concept" does not exist
LINE 1: ...ocabulary_id, concept_class_id, concept_code FROM concept WH...
                                                             ^
)
```
On PostgreSQL, you have to specify both the *database* and the *schema*. I've set the database in the `dbName` environmental variable, but I'm not sure where I should specify the schema. I think this is the root cause of the error.

**Comment by BenGlicksberg** [comment]
Thank you @schuemie. We have since integrated your/OHDSI's https://github.com/OHDSI/DatabaseConnector and https://github.com/OHDSI/SqlRender packages into the connection procedure. For PostgreSQL: server is used for the host field and schema for dbname.
