### ISSUE TITLE
Issues with connecting to local Postgres database

### ISSUE THREAD

**Issue by topspinj** [BenGlicksberg/ROMOP#3]
I'm have some issues establishing a connection to my local Postgres db. I've set up a Postgres db (as per instructions in `OHDSI/ETL-CMS`) with synthetic patient data. I've updated my .Renviron file with the following info:

```
driver = "postgresql"
host = "localhost"
username = {my_username}
password = ""
dbname = "ohdsi" (my db name)
port = "3306" 
```

I'm now trying to load ROMOP but I get the following error message:
```
Error: package or namespace load failed for ‘ROMOP’:
 .onLoad failed in loadNamespace() for 'ROMOP', details:
  call: DatabaseConnector::connect(dbms = tolower(Sys.getenv("driver")), 
  error: Error: database name not included in server string but is required for PostgreSQL. Please specify server as <host>/<database>
```
How do I include my database name in server string? 

Do I also have to indicate which schema I'm using? If so, where would I specify that? 

Any help would be much appreciated!

**Comment by BenGlicksberg** [comment]
Hi @topspinj, sorry for the delay. Will check on this and get back to you tomorrow at the latest

**Comment by MaximMoinat** [comment]
For Postgresql, the dbname is your schema name and the database name goes in the host field:
```
driver = "postgresql"
host = "localhost/ohdsi"
username = {my_username}
password = ""
dbname = {schema_name}
port = "3306" 
```

**Comment by topspinj** [comment]
@MaximMoinat this works - thanks!

**Comment by BenGlicksberg** [comment]
Thanks @MaximMoinat! Sorry for not getting back to you sooner @topspinj.
