### ISSUE TITLE
Is birth_datetime part of the CDM? 

### ISSUE THREAD

**Issue by topspinj** [BenGlicksberg/ROMOP#4]
`getDemographics()` assumes a `birth_datetime` column, but I've noticed that OHDSI's table creation [script](https://github.com/OHDSI/ETL-CMS/blob/51044ceea7ddd14d02275e2796f62f454016e238/SQL/create_CDMv5_tables.sql) doesn't include this column. So I'm wondering - has there been a recent change to CDM's person schema such that `birth_datetime` has been removed?

**Comment by BenGlicksberg** [comment]
Hey @topspinj, we used the DDL from [here](https://github.com/OHDSI/CommonDataModel/blob/master/PostgreSQL/OMOP%20CDM%20postgresql%20ddl.txt) which has it. It seems that link could be CMS specific? Regardless this is great to know, thank you. I will look into it to see if it makes sense removing that column requirement and replace it with one that is more universal.
