### ISSUE TITLE
makeDataOntology invalid_reason 

### ISSUE THREAD

**Issue by dramacloak** [BenGlicksberg/ROMOP#6]
DBMS:
postgresql
Error:
org.postgresql.util.PSQLException: ERROR: relation "concept" does not exist
  Position: 96
SQL:
SELECT concept_id, concept_name, domain_id, vocabulary_id, concept_class_id, concept_code FROM concept WHERE invalid_reason = '';
R version:
R version 3.5.2 (2018-12-20)
Platform:
x86_64-w64-mingw32
Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base
Other attached packages:
- ROMOP (0.3.0)

I got the error above when I ran ROMOP's makeDataOntology(declare=TRUE,store_ontology=TRUE) command in PostgreSQL which I fixed by using the schema name cdm instead of the database name OHDSI in the .Renviron file, however this returned:
Concept data loaded; data found for: 
0 unique domains.
0 unique vocabularies.
0 unique concept classes.
I suspect this would work if WHERE invalid_reason = ''; was changed to WHERE invalid_reason is null; instead, as running the above select statement doesn't work in the first case but does work when I make that change.

**Comment by dramacloak** [comment]
Further investigation revealed that the connection was not setup properly when the store_ontology is False. I've rebuilt my .Renviron file so that it connects to my Oracle database, however, I'm now getting the following errors:
> dataOntology <- makeDataOntology(declare=TRUE)
Retrieving concept data...
Connecting using Oracle driver
- using THIN to connect
Error in rJava::.jcall(jdbcDriver, "Ljava/sql/Connection;", "connect",  : 
  java.sql.SQLRecoverableException: IO Error: Invalid connection string format, a valid format is: "host:port:sid" 
- Trying using TNSName
Concept data loaded; data found for: 
0 unique domains.
0 unique vocabularies.
0 unique concept classes.
Warning message:
'SqlRender::translateSql' is deprecated.
Use 'translate' instead.
See help("Deprecated") 

I suspect the issue is in R/utils.R, specifically that the DatabaseConnector connection for non-mysql connections does not specify a port when it's being setup:
con <- DatabaseConnector::connect(dbms = tolower(Sys.getenv("driver")),
                   server = Sys.getenv("host"),
                   user = Sys.getenv("username"),
                   password = Sys.getenv("password"),
                   schema = Sys.getenv("dbname"))
For whatever reason, it's not finding the views that I have for my vocabulary tables (which are stored in a different schema than the cdm). 

I'm also probably using a newer version of the software, and thus translateSql is deprecated functionality. 

Thoughts on making ROMOP more robust to other databases like PostgreSQL and Oracle?

**Comment by BenGlicksberg** [comment]
Thanks for investigating and bringing this up. Responded by e-mail, but am working on the invalid_reason and port issues this week. Apologies for the inconvenience.

**Comment by BenGlicksberg** [comment]
Hi there @dramacloak , sorry for the delay. It seems I had made the changes a while back in dev branch but forgot to merge with master. Could you please check to see if the code from the dev branch works? Thanks again for your help.

**Comment by dramacloak** [comment]
Here's what I get when running the dev branch:

> devtools::install_github("BenGlicksberg/ROMOP", ref="dev", force=TRUE)
Downloading GitHub repo BenGlicksberg/ROMOP@dev
These packages have more recent versions available.
Which would you like to update?

 1:   assertthat   (0.2.0   -> 0.2.1 ) [CRAN]   2:   backports    (1.1.3   -> 1.1.4 ) [CRAN]
 3:   cli          (1.0.1   -> 1.1.0 ) [CRAN]   4:   data.table   (1.12.0  -> 1.12.2) [CRAN]
 5:   DatabaseC... (1.0.0   -> 1.1.0 ) [CRAN]   6:   digest       (0.6.18  -> 0.6.20) [CRAN]
 7:   dplyr        (0.8.0.1 -> 0.8.3 ) [CRAN]   8:   glue         (1.3.0   -> 1.3.1 ) [CRAN]
 9:   pillar       (1.3.1   -> 1.4.2 ) [CRAN]  10:   purrr        (0.3.0   -> 0.3.2 ) [CRAN]
11:   Rcpp         (1.0.0   -> 1.0.1 ) [CRAN]  12:   rJava        (0.9-10  -> 0.9-11) [CRAN]
13:   rlang        (0.3.1   -> 0.4.0 ) [CRAN]  14:   SqlRender    (1.6.0   -> 1.6.2 ) [CRAN]
15:   tibble       (2.0.1   -> 2.1.3 ) [CRAN]  16:   urltools     (1.7.2   -> 1.7.3 ) [CRAN]
17:   vctrs        (0.1.0   -> 0.2.0 ) [CRAN]  18:   CRAN packages only                     
19:   All                                      20:   None                                   

Enter one or more numbers separated by spaces, or an empty line to cancel
1: 20
Installing 1 packages: ellipsis
Installing package into ‘C:/Users/955990/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/ellipsis_0.2.0.1.zip'
Content type 'application/zip' length 43258 bytes (42 KB)
downloaded 42 KB

package ‘ellipsis’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\955990\AppData\Local\Temp\RtmpOcOzsl\downloaded_packages
√  checking for file 'C:\Users\955990\AppData\Local\Temp\RtmpOcOzsl\remotes22bc65df280\BenGlicksberg-ROMOP-a10c284/DESCRIPTION' (520ms)
-  preparing 'ROMOP':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'ROMOP_0.3.0.tar.gz'
   
Installing package into ‘C:/Users/955990/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'ROMOP' ...
** R
** byte-compile and prepare package for lazy loading
Warning: replacing previous import 'data.table::last' by 'dplyr::last' when loading 'ROMOP'
Warning: replacing previous import 'data.table::first' by 'dplyr::first' when loading 'ROMOP'
Warning: replacing previous import 'data.table::between' by 'dplyr::between' when loading 'ROMOP'
** help
*** installing help indices
  converting help for package 'ROMOP'
    finding HTML links ... done
    changeOutDirectory                      html  
    exploreConcepts                         html  
    findPatients                            html  
    getClinicalData                         html  
    getConditions                           html  
    getDemographics                         html  
    getDevices                              html  
    getEncounters                           html  
    getMeasurements                         html  
    getMedications                          html  
    getObservations                         html  
    getProcedures                           html  
    makeDataOntology                        html  
    showDataTypes                           html  
    summarizeDemographics                   html  
** building package indices
** testing if installed package can be loaded
*** arch - i386
Warning: replacing previous import 'data.table::between' by 'dplyr::between' when loading 'ROMOP'
Warning: replacing previous import 'data.table::first' by 'dplyr::first' when loading 'ROMOP'
Warning: replacing previous import 'data.table::last' by 'dplyr::last' when loading 'ROMOP'
Please refer to the ReadMe to set and format server credentials in the .Renviron file.
*** arch - x64
Warning: replacing previous import 'data.table::last' by 'dplyr::last' when loading 'ROMOP'
Warning: replacing previous import 'data.table::first' by 'dplyr::first' when loading 'ROMOP'
Warning: replacing previous import 'data.table::between' by 'dplyr::between' when loading 'ROMOP'
Please refer to the ReadMe to set and format server credentials in the .Renviron file.
* DONE (ROMOP)
In R CMD INSTALL
Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
> library(ROMOP)
Welcome to ROMOP: please refer to https://github.com/BenGlicksberg/ROMOP for detailed instructions on how to use package with examples.

Current OutDirectory is set to C:/Users/955990/Documents. Please use changeOutDirectory function to set.
 e.g., changeOutDirectory('path/to/outdir', create = TRUE) 

Now checking for required credentials and server connection (note this package will not function without them). Please wait...

Please refer to the ReadMe to set and format server credentials in the .Renviron file.
Warning messages:
1: replacing previous import ‘data.table::last’ by ‘dplyr::last’ when loading ‘ROMOP’ 
2: replacing previous import ‘data.table::first’ by ‘dplyr::first’ when loading ‘ROMOP’ 
3: replacing previous import ‘data.table::between’ by ‘dplyr::between’ when loading ‘ROMOP’ 
> dataOntology <- makeDataOntology(declare=TRUE)
Retrieving concept data...
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  java.lang.RuntimeException: Don't know how to translate from sql server to . Valid target dialects are sql server
In addition: Warning message:
'SqlRender::translateSql' is deprecated.
Use 'translate' instead.
See help("Deprecated") 
Error in rJava::is.jnull(connection@jConnection) : 
  trying to get slot "jConnection" from an object of a basic class ("NULL") with no slots
> exploreConcepts("ATC","A03AE")
Error: dataOntology does not exist. Please first run makeDataOntology.

**Comment by BenGlicksberg** [comment]
Just a quick note that I have added the NULL condition (instead of just "") for invalid_reason in makeDataOntology function

**Comment by dramacloak** [comment]
This issue was resolved in the latest release.
